from fastapi import FastAPI, Query, Response
import from fastapi import FastAPI, Query, Response
import requests
import time
from datetime import datetime, timezone

app = FastAPI()

# --- CONFIGURATION ---
BIN_ID = "69f60ccc36566621a818af6b" 
API_KEY = "$2a$10$e7Ap4ivHIhQer/PSEZXQmO.PO.oafbEncIR6ZIgQmGqCTBUm3b25W"
SOURCE_URL = "https://ayush-multi-api.vercel.app/api/num"

def get_remote_keys():
    """Fetches keys with extra headers to prevent 'Invalid Key' errors."""
    try:
        t = int(time.time())
        url = f"https://api.jsonbin.io/v3/b/{BIN_ID}/latest"
        headers = {
            "X-Master-Key": API_KEY,
            "X-Bin-Meta": "false",
            "Content-Type": "application/json",
            "Cache-Control": "no-cache", # Forces JSONBin to give fresh data
            "Pragma": "no-cache"
        }
        # Added params to double-check no cache is used
        params = {"nocache": t}
        req = requests.get(url, headers=headers, params=params, timeout=10)
        
        if req.status_code == 200:
            return req.json()
        else:
            print(f"Error: {req.status_code}")
            return {}
    except Exception as e:
        print(f"Fetch failed: {e}")
        return {}

@app.get("/")
async def get_data(response: Response, key: str = Query(...), mobile: str = Query(...)):
    # Standard security headers
    response.headers["Cache-Control"] = "no-store, no-cache, must-revalidate, max-age=0"
    
    clean_key = key.strip()
    keys_data = get_remote_keys()

    # 1. Improved Key Check (Check if data is empty first)
    if not keys_data:
        return {"success": False, "message": "DATABASE CONNECTION ERROR - TRY AGAIN"}

    if clean_key not in keys_data:
        return {
            "success": False, 
            "owner": "@Eshucording contact 8123561579", 
            "message": "INVALID KEY"
        }

    # 2. Expiry Logic
    expiry_date_str = keys_data[clean_key]
    try:
        # Check if the date format is YYYY-MM-DD
        expiry_date = datetime.strptime(expiry_date_str, "%Y-%m-%d").replace(tzinfo=timezone.utc)
        current_time = datetime.now(timezone.utc)

        if current_time > expiry_date:
            return {
                "success": False,
                "message": "KEY EXPIRED. To buy contact @Eshucording or 8123561579"
            }
    except:
        pass

    # 3. Fetch from Original API
    try:
        source_res = requests.get(f"{SOURCE_URL}?term={mobile}", timeout=10)
        if source_res.status_code != 200:
            return {"success": False, "message": "SOURCE API BUSY"}
        
        data = source_res.json()

        # 4. Remove Ayush and add Eshu Codex Branding
        if isinstance(data, dict):
            data.pop("developer", None)
            data["owner"] = "@Eshucording contact 8123561579"
            data["status"] = "Success"
            data["valid_until"] = expiry_date_str

        return data

    except Exception:
        return {"success": False, "message": "INTERNAL SERVER ERROR"}

import time
from datetime import datetime, timezone

app = FastAPI()

# --- CONFIGURATION ---
BIN_ID = "69f60ccc36566621a818af6b" 
API_KEY = "$2a$10$e7Ap4ivHIhQer/PSEZXQmO.PO.oafbEncIR6ZIgQmGqCTBUm3b25W"
SOURCE_URL = "https://ayush-multi-api.vercel.app/api/num"

def get_remote_keys():
    try:
        # Using nocache to ensure we get the latest keys generated by your bot
        t = int(time.time())
        url = f"https://api.jsonbin.io/v3/b/{BIN_ID}/latest?nocache=true&t={t}"
        headers = {"X-Master-Key": API_KEY, "X-Bin-Meta": "false"}
        req = requests.get(url, headers=headers, timeout=10)
        return req.json() if req.status_code == 200 else {}
    except:
        return {}

@app.get("/")
async def get_data(response: Response, key: str = Query(...), mobile: str = Query(...)):
    # 🚫 NO CACHE
    response.headers["Cache-Control"] = "no-store, no-cache, must-revalidate, max-age=0"
    
    clean_key = key.strip()
    keys_data = get_remote_keys()

    # 1. Check if Key exists in the bin
    if clean_key not in keys_data:
        return {
            "success": False, 
            "owner": "@Eshucording contact 8123561579", 
            "message": "INVALID KEY"
        }

    # 2. Expiry Logic
    expiry_date_str = keys_data[clean_key]
    try:
        # Standard format check (YYYY-MM-DD)
        expiry_date = datetime.strptime(expiry_date_str, "%Y-%m-%d").replace(tzinfo=timezone.utc)
        current_time = datetime.now(timezone.utc)

        if current_time > expiry_date:
            return {
                "success": False,
                "message": "KEY EXPIRED. To buy contact @Eshucording or 8123561579"
            }
    except Exception:
        # Fallback if your bot uses a different format, it still allows the request
        pass

    # 3. Fetch Data from Original API
    try:
        source_res = requests.get(f"{SOURCE_URL}?term={mobile}", timeout=10)
        if source_res.status_code != 200:
            return {"success": False, "message": "API SERVER BUSY"}
        
        data = source_res.json()

        # 4. Clean and Rebrand
        if "developer" in data:
            del data["developer"]
        
        # Adding your custom footer
        data["owner"] = "@Eshucording contact 8123561579"
        data["status"] = "Success"
        data["valid_until"] = expiry_date_str

        return data

    except Exception as e:
        return {"success": False, "message": "ERROR FETCHING DATA"}
    ist_now = datetime.now(timezone(timedelta(hours=5, minutes=30)))
    try:
        expiry_date = datetime.strptime(keys[clean_key], "%Y-%m-%d").replace(
            tzinfo=timezone(timedelta(hours=5, minutes=30))
        )
        remaining_days = (expiry_date - ist_now).days + 1
    except:
        remaining_days = 0

    if remaining_days <= 0:
        return {"success": False, "owner": "@Eshucording contact 8123561579", "message": "KEY EXPIRED"}

    # 3. Call Source API
    try:
        target_url = f"{SOURCE_API}?key={SOURCE_KEY}&query={mobile}"
        source_res = requests.get(target_url, timeout=15)
        
        if source_res.status_code != 200:
            return {"success": False, "message": "Gateway Offline"}

        source_data = source_res.json()

        # 🔥 BRANDING FIX: Overwrite the DEV and owner fields
        source_data["owner"] = "@Eshucording contact 8123561579"
        source_data["DEV"] = "Powered by @Eshucording number 8123561579"
        source_data["days_remaining"] = f"{remaining_days} Days"

        return source_data

    except:
        return {"success": False, "message": "Connection Error"}
    # 1. Clean the input key (Removes extra spaces)
    clean_key = key.strip()

    # 2. Get fresh keys from JSONBin
    keys = get_remote_keys()

    # 3. Check Key (Case-Sensitive check)
    if clean_key not in keys:
        return {
            "success": False,
            "owner": "@Eshucording contact 8123561579",
            "message": f"INVALID KEY: {clean_key}"
        }

    # 4. Check Expiry
    ist_now = datetime.now(timezone(timedelta(hours=5, minutes=30)))
    try:
        expiry_date = datetime.strptime(keys[clean_key], "%Y-%m-%d").replace(
            tzinfo=timezone(timedelta(hours=5, minutes=30))
        )
        remaining_days = (expiry_date - ist_now).days + 1
    except:
        remaining_days = 0

    if remaining_days <= 0:
        return {
            "success": False,
            "owner": "@Eshucording contact 8123561579",
            "message": "KEY EXPIRED"
        }

    # 5. Call Source API
    try:
        target_url = f"{SOURCE_API}?key={SOURCE_KEY}&query={mobile}"
        source_res = requests.get(target_url, timeout=15)
        
        if source_res.status_code != 200:
            return {"success": False, "message": "Gateway Offline"}

        source_data = source_res.json()
        source_data["owner"] = "@Eshucording contact 8123561579"
        source_data["days_remaining"] = f"{remaining_days} Days"

        return source_data

    except Exception as e:
        return {"success": False, "message": "Connection Timeout"}
